apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: hello
spec:
  schedule: "*/1 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          imagePullSecrets:
            - name : regcred
          containers:
          - name: hello
            image: mikelangelon/cronjob
            args:
            - /app/cronjob
          restartPolicy: OnFailure