apiVersion: v1
kind: Service
metadata:
  name: minio
  annotations:
    dev.okteto.com/auto-ingress: "true"
spec:
  type: ClusterIP
  ports:
  - name: "minio"
    port: 9000
  selector:
    app: minio

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: minio
spec:
  replicas: 1
  selector:
    matchLabels:
      app: minio
  template:
    metadata:
      labels:
        app: minio
    spec:
      containers:
        - image: minio/minio
          name: minio
          args:
            - server /data
          volumeMounts:
            - name: storage
              mountPath: /data
      volumes:
        - name: storage
          persistentVolumeClaim:
            claimName: minio-storage
            readOnly: false
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
    annotations:
    name: minio-storage
spec:
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: 1Gi



