apiVersion: v1
kind: Service
metadata:
  name: redis
  annotations:
    dev.okteto.com/auto-ingress: "true"
spec:
  type: ClusterIP  
  ports:
  - name: "redis"
    port: 6379
  selector:
    app: redis

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
        - image: redis
          name: redis
          volumeMounts:
            - name: storage
              mountPath: /data
      volumes:
        - name: storage
          persistentVolumeClaim:
            claimName: db-storage
            readOnly: false
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
    annotations:
    name: db-storage
spec:
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: 500Mi

    
          
